// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using TrincaBackEnd.Repositories;

namespace TrincaBackEnd.Migrations
{
    [DbContext(typeof(ChurrasDbContext))]
    partial class ChurrasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TrincaBackEnd.Models.Entities.Churras", b =>
                {
                    b.Property<int>("ChurrasId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Data");

                    b.Property<string>("Observacoes")
                        .IsRequired();

                    b.Property<string>("Titulo")
                        .IsRequired();

                    b.HasKey("ChurrasId");

                    b.ToTable("Churras");
                });

            modelBuilder.Entity("TrincaBackEnd.Models.Entities.Participante", b =>
                {
                    b.Property<int>("ParticipanteId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ChurrasId");

                    b.Property<bool>("ComBebida");

                    b.Property<decimal>("Contribuicao");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<bool>("Pago");

                    b.HasKey("ParticipanteId");

                    b.ToTable("Participantes");
                });
#pragma warning restore 612, 618
        }
    }
}
